// Auto-generated by generate-mappings.ts
// Maps logical chapter index (0-based) to spine index
// Usage: chapterMappings["v1"][0] = spine index of Chapter 1

export const chapterMappings: Record<string, number[]> = {
  "v1": [
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18
  ],
  "v2": [
    7,
    8,
    9,
    10,
    11,
    12,
    13
  ],
  "v3": [
    7,
    8,
    9,
    10,
    11,
    12,
    13
  ],
  "v4": [
    7,
    8,
    9,
    10,
    11
  ],
  "v4.5": [
    7,
    8,
    9,
    10,
    11,
    12,
    13
  ],
  "v5": [
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15
  ],
  "v6": [
    7,
    8,
    9,
    10,
    11,
    12,
    13
  ],
  "v7": [
    7,
    8,
    9,
    10,
    11,
    12,
    13
  ],
  "v7.5": [
    7,
    8,
    9,
    10,
    11,
    12
  ],
  "v8": [
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15
  ],
  "v9": [
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15
  ],
  "v10": [
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14
  ],
  "v11": [
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16
  ],
  "v11.5": [
    7,
    8,
    9,
    10,
    11,
    12,
    13
  ],
  "y2v1": [
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14
  ],
  "y2v2": [
    7,
    8,
    9,
    10,
    11,
    12,
    13
  ],
  "y2v3": [
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16
  ],
  "y2v4": [
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14
  ],
  "y2v4.5": [
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14
  ],
  "y2v5": [
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15
  ],
  "y2v6": [
    7,
    8,
    10,
    11,
    12,
    13,
    14
  ],
  "y2v7": [
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15
  ],
  "y2v8": [
    7,
    8,
    9,
    10,
    11,
    12,
    13
  ],
  "v0": [
    10,
    11,
    14,
    23,
    28,
    30,
    41,
    48
  ],
  "y2v9": [
    11,
    12,
    15,
    20,
    23,
    26,
    31,
    34,
    36,
    37,
    38
  ],
  "y2v9.5": [
    11,
    12,
    15,
    18,
    21,
    28,
    35,
    36,
    37
  ],
  "y2v10": [
    11,
    12,
    13,
    16,
    17,
    18,
    19,
    32,
    38,
    39
  ],
  "y2v11": [
    3,
    4,
    5,
    6,
    7,
    8,
    9
  ],
  "y2v12": [
    11,
    12,
    13,
    14,
    15,
    16,
    19,
    27,
    30,
    37,
    38,
    39
  ],
  "y2v12.5": [
    11,
    12,
    13,
    16,
    19,
    20,
    22,
    25,
    28,
    31,
    38,
    40,
    41,
    42
  ],
  "y3v1": [
    10,
    11,
    13,
    15,
    21,
    24,
    30,
    32,
    38,
    40
  ],
  "y3v2": [
    10,
    11,
    15,
    18,
    28,
    33,
    39,
    43,
    47
  ],
  "y3v3": [
    12,
    13,
    17,
    22,
    28,
    34,
    39,
    46,
    52
  ],
  "ss-y3-v1": [
    49,
    46,
    47,
    48,
    50,
    51,
    52
  ],
  "ss-y3-v2": [
    51,
    52,
    53,
    54,
    55
  ]
};

/**
 * Get the spine index for a logical chapter
 * @param volumeId - e.g., "v1"
 * @param logicalIndex - 0-based logical chapter index (Chapter 1 = 0)
 * @returns spine index, or logicalIndex + 1 if no mapping exists
 */
export function getSpineIndex(volumeId: string, logicalIndex: number): number {
    const mapping = chapterMappings[volumeId];
    if (mapping && mapping[logicalIndex]) {
        return mapping[logicalIndex];
    }
    return logicalIndex + 1; // Fallback to 1-based index
}
